"""Write the Julia right-hand side of the Fabbri-Linder model from cubie's float64 parse of the CellML file, so julia_cpu integrates the equations cubie does: `runner_scripts/generated/fabbri_linder_rhs.jl` (fabbri_linder_rhs!(du, u, ach, iso, t) with every literal in the real type of ach and the states in fabbri.STATE_ORDER, plus FABBRI_LINDER_Y0 and FABBRI_LINDER_STATES) and `fabbri_linder_rhs_check.json`, derivative values at random states that tests/test_julia_systems.jl checks the file against. Run under the cubie venv: `python runner_scripts/fabbri_export.py`."""

import json
import os
import sys

import numpy as np
import sympy as sp
from sympy.printing.julia import JuliaCodePrinter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fabbri  # noqa: E402

GENERATED_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")
RHS_PATH = os.path.join(GENERATED_DIR, "fabbri_linder_rhs.jl")
CHECK_PATH = os.path.join(GENERATED_DIR, "fabbri_linder_rhs_check.json")
CHECK_POINTS = 8
CHECK_SEED = 20260921


class _Printer(JuliaCodePrinter):
    """Julia with every float and rational as R(...), R the real type of the inputs, non-integer powers, logs and roots through NaNMath (NaN, not a DomainError, on a bad argument), Piecewise as nested ternaries so untaken branches never evaluate."""

    def __init__(self):
        super().__init__(settings={"user_functions": {"log": "NaNMath.log", "sqrt": "NaNMath.sqrt"}})

    def _print_Float(self, expr):
        return "R({0!r})".format(float(expr))

    def _print_Rational(self, expr):
        return "R({0!r})".format(float(expr))

    def _print_Pow(self, expr):
        if expr.exp.is_Integer:
            return super()._print_Pow(expr)
        return "NaNMath.pow({0}, {1})".format(self._print(expr.base), self._print(expr.exp))

    def _print_Piecewise(self, expr):
        branches = list(expr.args)
        if branches[-1].cond == sp.true:
            body = self._print(branches[-1].expr)
            branches = branches[:-1]
        else:
            body = "R(NaN)"
        for value, cond in reversed(branches):
            body = "({0} ? {1} : {2})".format(self._print(cond), self._print(value), body)
        return body


def load_system():
    """The float64 cubie system with the cascade on and the two analogue inputs as parameters."""
    from cubie import load_cellml_model
    system = load_cellml_model(fabbri.MODEL_PATH, precision=np.float64, name="fabbri_linder_export",
                               parameters=[fabbri.ACH_PARAMETER, fabbri.ISO_PARAMETER],
                               voltage_variable=fabbri.VOLTAGE_RAW)
    system.set_constants({fabbri.ANS_CONSTANT: 1.0})
    return system


def assignments(system):
    """[(name, sympy rhs, is_derivative)] of every parsed equation, in an order that assigns each name before its use."""
    from cubie.odesystems.symbolic.engine import to_sympy
    equations = system.equations
    raw = [(str(to_sympy(lhs)), to_sympy(rhs), lhs in equations.state_symbols) for lhs, rhs in equations.ordered]
    assigned = {name for name, _, _ in raw}
    emitted, out, remaining = set(), [], list(raw)
    while remaining:
        deferred = []
        for item in remaining:
            if {s.name for s in item[1].free_symbols if s.name in assigned} <= emitted:
                out.append(item)
                emitted.add(item[0])
            else:
                deferred.append(item)
        if len(deferred) == len(remaining):
            raise RuntimeError("assignment dependency cycle near " + ", ".join(i[0] for i in deferred[:5]))
        remaining = deferred
    return out


def julia_source(system, ordered):
    """The generated module text."""
    states = list(system.initial_values.names)
    if sorted(states) != sorted(fabbri.STATE_ORDER):
        raise RuntimeError("cubie's states {0} are not fabbri.STATE_ORDER".format(states))
    if list(system.parameters.names) != [fabbri.ACH_PARAMETER, fabbri.ISO_PARAMETER]:
        raise RuntimeError("unexpected parameters " + str(list(system.parameters.names)))
    printer = _Printer()
    index = {"d" + name: position + 1 for position, name in enumerate(fabbri.STATE_ORDER)}
    derivatives = [name for name, _, is_derivative in ordered if is_derivative]
    if sorted(derivatives) != sorted(index):
        raise RuntimeError("derivatives {0} do not match the states".format(derivatives))
    lines = ["# Generated by runner_scripts/fabbri_export.py from runner_scripts/models/fabbri_linder.cellml through "
             "cubie's float64 parse; do not edit. fabbri_linder_rhs!(du, u, ach, iso, t) evaluates the Fabbri-Linder "
             "right-hand side with the states in fabbri.STATE_ORDER and the cascade switch on; every literal takes the real type "
             "of ach, so a dual-number u differentiates through plain constants.",
             "import NaNMath", "",
             "function fabbri_linder_rhs!(du, u, ach, iso, t)", "    R = typeof(ach)"]
    for position, name in enumerate(fabbri.STATE_ORDER):
        lines.append("    {0} = u[{1}]".format(name, position + 1))
    # Every literal is in the inputs' real type R, never in the element type of u: a dual-number literal divided by
    # ACh = 0 would carry NaN partials, where the plain value is a finite limit.
    lines.append("    {0} = ach".format(fabbri.ACH_PARAMETER))
    lines.append("    {0} = iso".format(fabbri.ISO_PARAMETER))
    for name in system.constants.names:
        lines.append("    {0} = R({1!r})".format(name, float(system.constants.get_values([name]))))
    for name, rhs, is_derivative in ordered:
        code = printer.doprint(rhs)
        if is_derivative:
            lines.append("    du[{0}] = {1}".format(index[name], code))
        else:
            lines.append("    {0} = {1}".format(name, code))
    lines += ["    return nothing", "end", ""]
    y0 = {name: float(system.initial_values.get_values([name])) for name in states}
    lines.append("const FABBRI_LINDER_Y0 = [{0}]".format(", ".join(repr(y0[name]) for name in fabbri.STATE_ORDER)))
    lines.append("const FABBRI_LINDER_STATES = [{0}]".format(", ".join('"{0}"'.format(n) for n in fabbri.STATE_ORDER)))
    lines.append("")
    return "\n".join(lines)


def check_points(system, ordered):
    """Derivatives at CHECK_POINTS random states (the initial state scaled by 1 + 0.1 N(0, 1) per state) and inputs, evaluated from the sympy assignments in float64 with untaken Piecewise branches free to overflow."""
    rng = np.random.default_rng(CHECK_SEED)
    y0 = np.array([float(system.initial_values.get_values([name])) for name in fabbri.STATE_ORDER])
    u = y0[None, :] * (1.0 + 0.1 * rng.standard_normal((CHECK_POINTS, len(y0))))
    ach = rng.uniform(0.0, fabbri.ACH_MAX_NM, CHECK_POINTS)
    iso = rng.uniform(0.0, fabbri.ISO_MAX_NM, CHECK_POINTS)
    t = rng.uniform(0.0, 2.0, CHECK_POINTS)
    compiled = []
    for name, rhs, is_derivative in ordered:
        free = sorted(rhs.free_symbols, key=lambda s: s.name)
        compiled.append((name, free, sp.lambdify(free, rhs, modules=["numpy"]), is_derivative))
    constants = {name: np.float64(system.constants.get_values([name])) for name in system.constants.names}
    du = np.zeros_like(u)
    index = {"d" + name: position for position, name in enumerate(fabbri.STATE_ORDER)}
    with np.errstate(all="ignore"):
        for point in range(CHECK_POINTS):
            env = dict(constants)
            env.update(zip(fabbri.STATE_ORDER, u[point]))
            env[fabbri.ACH_PARAMETER] = np.float64(ach[point])
            env[fabbri.ISO_PARAMETER] = np.float64(iso[point])
            env["t"] = np.float64(t[point])
            for name, free, fn, is_derivative in compiled:
                value = np.float64(fn(*(env[s.name] for s in free)))
                env[name] = value
                if is_derivative:
                    du[point, index[name]] = value
    if not np.isfinite(du).all():
        raise RuntimeError("a check point has a non-finite derivative")
    return {"states": list(fabbri.STATE_ORDER), "u": u.tolist(), "ach": ach.tolist(), "iso": iso.tolist(),
            "t": t.tolist(), "du": du.tolist()}


def main():
    system = load_system()
    ordered = assignments(system)
    os.makedirs(GENERATED_DIR, exist_ok=True)
    with open(RHS_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(julia_source(system, ordered))
    with open(CHECK_PATH, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(check_points(system, ordered), handle)
    print(RHS_PATH)
    print(CHECK_PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
