"""Shared protocol constants and helpers for the work-precision (wp) sweeps.

Every framework's `wp` mode runs the same Lorenz ensemble at N = 32768 (the
numerical cross-check size) and sweeps the controls it supports:

* fixed-step frameworks use dt in DTS (dyadic fractions of the t=1 duration,
  so save and end boundaries are exact in binary floating point), and
* adaptive frameworks use rtol = atol in TOLS.

For each setting the solve is timed with the established protocol (one
untimed warmup, ``timeit.repeat(..., number=1)``, ``min * 1000`` ms) and the
solution error is computed against the Float64 golden reference
(``data/numerical/golden_lorenz_32768.csv``, generated by
``runner_scripts/golden/generate_golden.jl``) as the ensemble l2 norm of the
final-state difference:  ``err = sqrt(mean((final - golden)**2))`` over the
(32768, 3) array — the same final-error metric used by
DiffEqDevTools.WorkPrecisionSet.

Rows ``<setting> <time_ms> <error>`` are written (mode "w" — a wp file always
holds exactly one full sweep) to
``data/<FRAMEWORK>/<Prefix>_wp_<fixed|adaptive>_<os>_<gpu>.txt``.

The Julia writer mirrors these constants; keep them in sync.
"""

import os

import numpy as np

# Sweep grids (canonical — mirrored in bench_lorenz_gpu.jl and the MPGOS
# runner; keep in sync).
DTS = [2.0 ** -k for k in range(4, 14)]        # 1/16 .. 1/8192, 10 points
TOLS = [10.0 ** -k for k in range(2, 9)]       # 1e-2 .. 1e-8, 7 points

N_WP = 32768

GOLDEN_PATH = os.path.join("data", "numerical", "golden_lorenz_32768.csv")


def load_golden():
    """Load the Float64 golden final states, shape (N_WP, 3)."""
    if not os.path.isfile(GOLDEN_PATH):
        raise FileNotFoundError(
            "{0} not found - generate it first with "
            "`julia -t auto --project=. runner_scripts/golden/generate_golden.jl`"
            .format(GOLDEN_PATH))
    golden = np.loadtxt(GOLDEN_PATH, delimiter=",")
    if golden.shape != (N_WP, 3):
        raise ValueError("golden reference has shape {0}, expected ({1}, 3)"
                         .format(golden.shape, N_WP))
    return golden


def ensemble_error(final_states, golden):
    """l2-at-final error over the ensemble, computed in float64."""
    diff = np.asarray(final_states, dtype=np.float64) - golden
    return float(np.sqrt(np.mean(diff ** 2)))


def wp_outfile(framework_dir, prefix, mode, dataset_key):
    """Path of the wp output file under data/<package>/<key>; creates the directory."""
    d = os.path.join("data", framework_dir, dataset_key)
    os.makedirs(d, exist_ok=True)
    return os.path.join(d, "{0}_wp_{1}.txt".format(prefix, mode))
