"""Shared protocol for the numerical-equivalence (ne) sweeps.

The ne suite compares cubie against raw DifferentialEquations.jl, both
running in Float32, across every algorithm the two stacks mutually support.
Unlike the wp sweeps (error vs runtime), ne is a fixed-step error-vs-dt
convergence study: for each algorithm both sides integrate the same Lorenz
ensemble at every dt in DTS_NE and the final states are compared against the
Float64 golden reference and against each other.

Protocol:

* Problem: Lorenz, sigma=10, beta=8/3, x0=(1,0,0), t in [0,1], rho swept
  over [0, 21] at N_NE = 1024 trajectories. The Float32 rho grid is read
  from the golden file so every consumer integrates bit-identical inputs.
* Golden: ``data/numerical/golden_ne_lorenz_1024.csv`` (rho,x,y,z rows,
  Float64, Vern9 at tol 1e-13; generated by generate_golden_ne.jl).
  Machine independent.
* Algorithms: ``algorithms.csv`` next to this module — one row per cubie
  algorithm alias with the matching DifferentialEquations.jl constructor
  expression, its theoretical order, and an ``adaptive`` flag marking the
  mutual adaptive set. Both runners consume this file. erk-family rows run
  no fixed sweep.
* dt grid: DTS_NE — dyadic fractions of the t=1 duration so every dt, save
  and end boundary is exact in binary floating point (Float32 included).
* Outputs: one CSV per algorithm, rows ``dt,traj,x,y,z`` (traj is the
  0-based trajectory index), final states at t=1 in the solver's Float32
  output promoted to decimal text.
  - DifferentialEquations.jl (CPU, machine independent):
      ``data/numerical_equivalence/julia/<alias>.csv``
  - cubie (GPU, keyed per machine like every other benchmark output):
      ``data/numerical_equivalence/cubie/<os>_<gpu>/<alias>.csv``

The Julia runner (ne_diffeq.jl) mirrors these constants; keep in sync.
"""

import csv
import os

import numpy as np

# Dyadic dt grid, 2^-1 .. 2^-13; the small-dt end resolves the fp-precision tail.
DTS_NE = [2.0 ** -k for k in range(1, 14)]

# Adaptive sweep: atol = rtol tolerance grid.
TOLS_NE = [10.0 ** -k for k in range(2, 9)]

DT0_NE = 0.01
DT_MIN_NE = 1e-6
DT_MAX_NE = 0.5

N_NE = 1024

GOLDEN_NE_PATH = os.path.join("data", "numerical", "golden_ne_lorenz_1024.csv")

ALGORITHMS_CSV = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "algorithms.csv")

JULIA_NE_DIR = os.path.join("data", "numerical_equivalence", "julia")
CUBIE_NE_DIR = os.path.join("data", "numerical_equivalence", "cubie")


def load_algorithms(name="all"):
    """Return the mutual algorithm table as a list of dicts.

    Keys: ``cubie_alias``, ``julia_expr``, ``order`` (int), ``family``,
    ``adaptive`` (bool — cubie carries an embedded error estimate, so the
    algorithm belongs to the mutual adaptive sweep), ``notes``.
    """
    with open(ALGORITHMS_CSV, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        row["order"] = int(row["order"])
        row["adaptive"] = row["adaptive"].strip().lower() == "true"
    if name != "all":
        rows = [row for row in rows if row["cubie_alias"] == name]
        if not rows:
            raise SystemExit("unknown algorithm '{}'; see algorithms.csv".format(name))
    return rows


def runs_fixed(row):
    """Whether the algorithm runs the fixed-step dt sweep (non-erk families)."""
    return row["family"] != "erk"


def cubie_default_controller(alias, family, order, force_pi=True):
    """Cubie's resolved controller settings for a default-tier solve.

    Mirrors cubie's resolution: family default table, then controller
    config class defaults for unset keys. ``force_pi`` overrides the
    table's controller with ``"pi"``. Gains resolve at ``order``; cubie
    imports lazily. Returns None when the family has no adaptive table.
    """
    from cubie.integrators.algorithms import (generic_dirk, generic_erk,
                                              generic_firk,
                                              generic_rosenbrock_w,
                                              crank_nicolson)
    tables = {
        "dirk": generic_dirk.DIRK_ADAPTIVE_DEFAULTS,
        "erk": generic_erk.ERK_ADAPTIVE_DEFAULTS,
        "firk": generic_firk.FIRK_ADAPTIVE_DEFAULTS,
        "rosenbrock": generic_rosenbrock_w.ROSENBROCK_ADAPTIVE_DEFAULTS,
    }
    if alias == "crank_nicolson":
        table = crank_nicolson.CN_DEFAULTS
    elif family in tables:
        table = tables[family]
    else:
        return None
    resolved = {
        # PI config class defaults (adaptive_PI_controller.py /
        # adaptive_step_controller.py) for keys the family table omits.
        "step_controller": "pi", "kp": 0.7, "ki": -0.4, "safety": 0.9,
        "min_gain": 0.2, "max_gain": 10.0,
    }
    for key, value in dict(table.step_controller).items():
        if callable(value):
            value = value(order)
        resolved[key] = value
    if force_pi:
        resolved["step_controller"] = "pi"
    resolved.pop("deadband_min", None)
    resolved.pop("deadband_max", None)
    return resolved


def controllers_equal(a, b, rel_tol=1e-9):
    """Whether two controller-settings dicts request the same controller.

    Controller names compare exactly, numeric keys to ``rel_tol``; a key
    present on one side only makes the dicts unequal.
    """
    if a is None or b is None:
        return False
    if a.get("step_controller") != b.get("step_controller"):
        return False
    keys = (set(a) | set(b)) - {"step_controller"}
    for key in keys:
        if key not in a or key not in b:
            return False
        va, vb = float(a[key]), float(b[key])
        if not np.isclose(va, vb, rtol=rel_tol, atol=0.0):
            return False
    return True


def algorithm_names():
    return ["all"] + [row["cubie_alias"] for row in load_algorithms()]


def load_golden_ne():
    """Load the golden file; returns (rho, states) float64 arrays.

    rho has shape (N_NE,) and holds the float32-rounded parameter grid;
    states has shape (N_NE, 3) with the Float64 reference final states.
    """
    if not os.path.isfile(GOLDEN_NE_PATH):
        raise FileNotFoundError(
            "{0} not found - generate it first with `julia -t auto --project=. "
            "runner_scripts/numerical_equivalence/generate_golden_ne.jl`"
            .format(GOLDEN_NE_PATH))
    data = np.loadtxt(GOLDEN_NE_PATH, delimiter=",")
    if data.shape != (N_NE, 4):
        raise ValueError("golden ne reference has shape {0}, expected ({1}, 4)"
                         .format(data.shape, N_NE))
    return data[:, 0], data[:, 1:]


def ensemble_error(final_states, golden_states):
    """l2-at-final error over the ensemble, computed in float64.

    Same metric as the wp sweeps: sqrt(mean((final - golden)**2)) over the
    (N_NE, 3) array.
    """
    diff = np.asarray(final_states, dtype=np.float64) - golden_states
    return float(np.sqrt(np.mean(diff ** 2)))


def ensemble_error_masked(final_states, golden_states, mask):
    """l2-at-final error over a masked subset of the ensemble, in float64.

    ``mask`` is a boolean (N_NE,) array selecting the trajectories to include
    (e.g. the trajectories both stacks converged on). Returns NaN when the
    mask selects nothing, so a fully non-converged point drops out of the
    comparison rather than contaminating it.
    """
    mask = np.asarray(mask, dtype=bool)
    if not mask.any():
        return float("nan")
    diff = (np.asarray(final_states, dtype=np.float64)[mask]
            - np.asarray(golden_states, dtype=np.float64)[mask])
    return float(np.sqrt(np.mean(diff ** 2)))


def _converged_from_rows(sel, arr):
    """Per-trajectory converged mask for one dt/tol block.

    A trajectory counts as converged iff it BOTH claims success and produced
    a finite final state, so the two stacks are measured the same way. cubie
    has no retcode column and signals a failed solve with NaN, so its flag is
    pure finiteness. The Julia runner writes a ``converged`` column (1/0 from
    each trajectory's SciML retcode); that is AND-ed with finiteness because an
    explicit fixed step can overflow to NaN/Inf while still returning a
    ``Success`` retcode — without the finite check those would be miscounted
    as converged and inflate the cubie-vs-julia non-convergence gap.
    """
    finite = np.isfinite(arr).all(axis=1)
    if sel and "converged" in sel[0] and sel[0]["converged"] not in ("", None):
        flag = np.array([str(r.get("converged", "")).strip() == "1"
                         for r in sel], dtype=bool)
        return flag & finite
    return finite


def read_ne_csv_masked(path):
    """Like :func:`read_ne_csv` but also returns a per-trajectory mask.

    Returns dict {dt: (finals (N_NE, 3) float64, converged (N_NE,) bool)}.
    """
    out = {}
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    dts = sorted({float(row["dt"]) for row in rows}, reverse=True)
    for dt in dts:
        sel = [row for row in rows if float(row["dt"]) == dt]
        sel.sort(key=lambda row: int(row["traj"]))
        arr = np.array([[float(row["x"]), float(row["y"]), float(row["z"])]
                        for row in sel], dtype=np.float64)
        out[dt] = (arr, _converged_from_rows(sel, arr))
    return out


def read_ne_adaptive_csv_masked(path):
    """Like :func:`read_ne_adaptive_csv` but also returns a converged mask.

    Returns dict {tol: (finals (N_NE, 3) float64, converged (N_NE,) bool,
    naccept, nreject)} with naccept/nreject as in :func:`read_ne_adaptive_csv`.
    """
    out = {}
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    tols = sorted({float(row["tol"]) for row in rows}, reverse=True)
    for tol in tols:
        sel = [row for row in rows if float(row["tol"]) == tol]
        sel.sort(key=lambda row: int(row["traj"]))
        arr = np.array([[float(row["x"]), float(row["y"]), float(row["z"])]
                        for row in sel], dtype=np.float64)
        conv = _converged_from_rows(sel, arr)

        def counts(field):
            vals = [row.get(field, "") for row in sel]
            if any(v not in ("", None) for v in vals):
                return np.array([float(v) if v not in ("", None) else np.nan
                                 for v in vals])
            return None
        out[tol] = (arr, conv, counts("naccept"), counts("nreject"))
    return out


def julia_ne_file(alias):
    """Path of the machine-independent DifferentialEquations.jl output."""
    return os.path.join(JULIA_NE_DIR, "{0}.csv".format(alias))


def cubie_ne_file(alias, dataset_key):
    """Path of the per-machine cubie output under a key dir; creates it."""
    d = os.path.join(CUBIE_NE_DIR, dataset_key)
    os.makedirs(d, exist_ok=True)
    return os.path.join(d, "{0}.csv".format(alias))


def julia_ne_adaptive_file(alias):
    """Julia adaptive-sweep output (rows tol,traj,x,y,z,naccept,nreject)."""
    return os.path.join(JULIA_NE_DIR, "{0}_adaptive.csv".format(alias))


def cubie_ne_adaptive_file(alias, tier, dataset_key):
    """Cubie adaptive-sweep output per controller tier: "default" or "matched"."""
    d = os.path.join(CUBIE_NE_DIR, dataset_key)
    os.makedirs(d, exist_ok=True)
    return os.path.join(d, "{0}_adaptive_{1}.csv".format(alias, tier))


CONTROLLER_CONSTANTS_CSV = os.path.join(JULIA_NE_DIR,
                                        "controller_constants.csv")


def load_controller_constants():
    """Julia's resolved default-controller constants, keyed by cubie alias.

    Written by ne_diffeq.jl. Values: controller (type name), beta1, beta2,
    qmin, qmax, gamma, order (classical), floats parsed; missing numeric
    fields come back as None.
    """
    if not os.path.isfile(CONTROLLER_CONSTANTS_CSV):
        raise FileNotFoundError(
            "{0} not found - run the Julia adaptive sweep first "
            "(runner_scripts/numerical_equivalence/ne_diffeq.jl)"
            .format(CONTROLLER_CONSTANTS_CSV))
    out = {}
    with open(CONTROLLER_CONSTANTS_CSV, newline="") as f:
        for row in csv.DictReader(f):
            entry = {"controller": row["controller"]}
            for key in ("beta1", "beta2", "qmin", "qmax", "gamma", "order"):
                raw = row.get(key, "")
                entry[key] = float(raw) if raw not in ("", None) else None
            out[row["cubie_alias"]] = entry
    return out


def write_ne_csv(path, per_dt_finals):
    """Write an ne output file (mode "w" — one file holds one full sweep).

    ``per_dt_finals`` is a list of (dt, finals) pairs where finals is an
    (N_NE, 3) array of Float32 final states.
    """
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["dt", "traj", "x", "y", "z"])
        for dt, finals in per_dt_finals:
            for j in range(finals.shape[0]):
                w.writerow(["{0:.10g}".format(dt), j,
                            repr(float(finals[j, 0])),
                            repr(float(finals[j, 1])),
                            repr(float(finals[j, 2]))])


def read_ne_csv(path):
    """Read an ne output file; returns dict {dt: (N_NE, 3) float64 array}."""
    out = {}
    with open(path, newline="") as f:
        r = csv.DictReader(f)
        rows = list(r)
    dts = sorted({float(row["dt"]) for row in rows}, reverse=True)
    for dt in dts:
        sel = [row for row in rows if float(row["dt"]) == dt]
        sel.sort(key=lambda row: int(row["traj"]))
        arr = np.array([[float(row["x"]), float(row["y"]), float(row["z"])]
                        for row in sel], dtype=np.float64)
        out[dt] = arr
    return out


def write_ne_adaptive_csv(path, per_tol_results):
    """Write an adaptive ne output file (one full sweep per file).

    ``per_tol_results`` is a list of (tol, finals, naccept, nreject) where
    finals is (N_NE, 3) float32 and naccept/nreject are per-trajectory int
    arrays or None when the stack does not report step counts.
    """
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["tol", "traj", "x", "y", "z", "naccept", "nreject"])
        for tol, finals, naccept, nreject in per_tol_results:
            for j in range(finals.shape[0]):
                w.writerow(["{0:.10g}".format(tol), j,
                            repr(float(finals[j, 0])),
                            repr(float(finals[j, 1])),
                            repr(float(finals[j, 2])),
                            "" if naccept is None else int(naccept[j]),
                            "" if nreject is None else int(nreject[j])])


def read_ne_adaptive_csv(path):
    """Read an adaptive ne file.

    Returns dict {tol: (finals, naccept, nreject)} with finals (N_NE, 3)
    float64 and naccept/nreject float64 arrays (NaN where unreported).
    """
    out = {}
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    tols = sorted({float(row["tol"]) for row in rows}, reverse=True)
    for tol in tols:
        sel = [row for row in rows if float(row["tol"]) == tol]
        sel.sort(key=lambda row: int(row["traj"]))
        arr = np.array([[float(row["x"]), float(row["y"]), float(row["z"])]
                        for row in sel], dtype=np.float64)
        def counts(field):
            vals = [row.get(field, "") for row in sel]
            if any(v not in ("", None) for v in vals):
                return np.array([float(v) if v not in ("", None) else np.nan
                                 for v in vals])
            return None
        out[tol] = (arr, counts("naccept"), counts("nreject"))
    return out
